# .pre-commit-config.yaml
repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Updated to latest stable version
    hooks:
      - id: black
        language_version: python3
        files: ^apps/ai-agent/.*\.py$

  # isort - Import statement organizer
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1  # Updated to latest stable version
    hooks:
      - id: isort
        args: ["--profile", "black"]  # Make isort compatible with black
        files: ^apps/ai-agent/.*\.py$

  # Pre-commit hooks for general file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Updated to latest stable version
    hooks:
      - id: end-of-file-fixer
        files: ^apps/ai-agent/
      - id: trailing-whitespace
        files: ^apps/ai-agent/
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']  # Limit file size to 10MB
      - id: check-merge-conflict
      - id: check-toml
        files: ^apps/ai-agent/.*\.toml$
      - id: debug-statements
        files: ^apps/ai-agent/.*\.py$
      - id: name-tests-test
        files: ^apps/ai-agent/.*\.py$

  # Flake8 - Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Updated to latest stable version
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-import-order]
        args: [
          "--max-line-length=88",  # Match black's line length
          "--extend-ignore=E203,W503"  # Ignore conflicts with black
        ]
        files: ^apps/ai-agent/.*\.py$

  # mypy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports]
        files: ^apps/ai-agent/.*\.py$

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: ["-r", "apps/ai-agent/src/"]
        files: ^apps/ai-agent/.*\.py$
        exclude: ^apps/ai-agent/tests/